version: '3.8'

services:
  telegram_bot:
    build: 
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=YOURTOKEN
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
      - OPERATOR_PASSWORD=password
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - ./base:/var/lib/postgresql/data
    restart: always
